XpressAI/SparkCyclone

- src/main/resources/com/nec/arrow/functions/cpp/transfer-definitions.hpp
- src/main/scala/com/nec/spark/agile/CExpressionEvaluation.scala
- src/main/scala/com/nec/spark/agile/StringProducer.scala
- src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala
- src/test/scala/com/nec/cmake/functions/WordsCheckSpec.scala
Results were being mixed up due to subtle bugs in String production.
The fix was to:
- Create some base checks with ScalaCheck for identity copy
- Create some base checks with ScalaCheck for filtered copy
- Then iterate until these tests pass.
> Fix String production bug

- src/main/scala/com/nec/ve/VeKernelCompiler.scala
To re-enable You need to pass `spark.com.nec.spark.ncc.profile-target="host:port"`
> Disable profiling by default.

- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/SparkExpressionToCExpression.scala
- src/main/scala/com/nec/spark/agile/StringHole.scala
- src/main/scala/com/nec/spark/agile/groupby/ConvertNamedExpression.scala
- src/main/scala/com/nec/spark/agile/groupby/GroupByPartialGenerator.scala
- src/main/scala/com/nec/spark/planning/TransformUtil.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/test/scala/com/nec/cmake/eval/OldUnifiedGroupByFunctionGeneration.scala
- src/test/scala/com/nec/cmake/eval/StringHoleEvaluationSpec.scala
- src/test/scala/com/nec/cmake/functions/IncludeTCPDebugSpec.scala
- src/test/scala/com/nec/cmake/functions/WordsCheckSpec.scala
- src/test/scala/com/nec/spark/agile/StringHoleSpec.scala
- src/test/scala/com/nec/spark/agile/groupby/ConvertNamedExpressionSpec.scala
- tests/tpchbench/src/main/scala/sparkcyclone/tpch/TPCHBenchmark.scala
This framework allows us to handle String expressions in a vector form, and does it in a fast way for LIKE-like operations.
Generated code for the fast version (on by default):
```c++
std::vector<int> slowStringEvaluation_1359651405(input_0->count);
frovedis::words slowStringEvaluation_words_1359651405 = varchar_vector_to_words(input_0);
std::vector<size_t> slowStringEvaluation_matching_ids_1359651405 = frovedis::like(slowStringEvaluation_words_1359651405.chars,(const vector<size_t>&)(slowStringEvaluation_words_1359651405.starts),
(const vector<size_t>&)(slowStringEvaluation_words_1359651405.lens),
"%e%");
for ( int i = 0; i < input_0->count; i++) { 
slowStringEvaluation_1359651405[i] = 0;
}
for(int i = 0; i < slowStringEvaluation_matching_ids_1359651405.size(); i++) { …
```
> String holes for handling string operations in a vector form

- .github/workflows/tpc.yml
- build.sbt
- src/test/scala/com/nec/spark/agile/SparkSanityTests.scala
This is so that we would be able to consistently review the whole stack of things, including plans and such.
The output is located in `target/test-html`.
> Run TPC tests on the VE, and report them in this GitHub action

- src/main/scala/com/nec/spark/SparkCycloneExecutorPlugin.scala
- src/main/scala/com/nec/spark/planning/VeCachedBatchSerializer.scala
- src/main/scala/com/nec/spark/planning/VeColBatchConverters.scala
- src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
- src/test/scala/com/nec/ve/RDDSpec.scala
- tests/tpchbench/src/main/scala/sparkcyclone/tpch/TPCHBenchmark.scala
To remove any data cached on the VE upon Executor shutdown.
Change `  var CleanUpCache: Boolean = true` to `false` in order to disable this in case causes issues.
Also, enabled the rough double matching for some other queries.
> Introduce a simple cache clean-up

- .github/workflows/benchmark-collector.yml
- build.sbt
- tpcbench-run/src/main/scala/sc/RunBenchmarksApp.scala
- tpcbench-run/src/main/scala/sc/RunDatabase.scala
- tpcbench-run/src/main/scala/sc/RunOptions.scala
- tpcbench-run/src/test/scala/sc/TpcBenchSpec.scala
- Support `all`
- Save into an HTML file available at `/tpc-html/`summary/` on the website.
> Improvements in benchmark runner

- .github/workflows/benchmark-collector-all.yml
- .github/workflows/benchmark-collector.yml
- .github/workflows/main.yml
- src/main/scala/com/nec/spark/SparkCycloneExecutorPlugin.scala
- src/main/scala/com/nec/spark/planning/SupportsVeColBatch.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/VeCachedBatchSerializer.scala
- src/main/scala/com/nec/spark/planning/VeColBatchConverters.scala
- src/main/scala/com/nec/spark/planning/VeColColumnarVector.scala
- src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala
- src/main/scala/com/nec/spark/planning/plans/VectorEngineToSparkPlan.scala
- src/main/scala/com/nec/ve/VeColBatch.scala
- src/test/scala/com/nec/spark/BenchTestingPossibilities.scala
- src/test/scala/com/nec/spark/SparkAdditions.scala
- src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
- src/test/scala/com/nec/tpc/TPCHVESqlSpec.scala
- src/test/scala/com/nec/ve/RDDSpec.scala
- tpcbench-run/src/main/scala/sc/GitHubInput.scala
- tpcbench-run/src/main/scala/sc/RunOptions.scala
- By default, in the plugin it is false
- When running in GitHub flows, it is `true`
- When running TPC correctness tests, it is `true`
- Fix issues with regards to caching correctness and clean-up correctness. We were sometimes trying to reuse cached data that got free'd.
> Add FailFast option

- .github/workflows/unittests-cmake.yml
- .github/workflows/unittests-ve.yml
- .github/workflows/unittests.yml
- When a PR is ready for review, automatically run tpc, cmake, and vectorengine and plain JVM unit tests.
We should work through Draft PR first
This should catch and expose any issues much more rapidly.
> Add more automation in terms of GitHub actions

- .github/workflows/unittests-cmake.yml
- .github/workflows/unittests-ve.yml
The unit tests don't seem to create a test-html folder so there's nothing to copy.
> Remove copy to sparkcyclone.io step in unit tests.

- src/main/scala/com/nec/arrow/ArrowEncodingSettings.scala
- src/main/scala/com/nec/cache/ArrowBasedCacheSerializer.scala
- src/main/scala/com/nec/cache/SparkInternalRowsToArrowColumnarBatches.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala
- src/main/scala/com/nec/spark/planning/plans/VeAmplifyBatchesPlan.scala
- src/main/scala/com/nec/util/BatchAmplifier.scala
- src/main/scala/com/nec/ve/VeProcess.scala
- src/main/scala/com/nec/ve/colvector/VeColBatch.scala
- src/test/scala/com/nec/cache/SparkInternalRowsToArrowColumnarBatchesTest.scala
- src/test/scala/com/nec/util/BatchAmplifierSpec.scala
- src/test/scala/com/nec/ve/DualModeVESpec.scala
This gathers sequences of small input batches and fuses them to pass into the next rows. It is intended to reduce the overall number of calls to the VE, and process significantly larger batches.
- Add new customization say that a target batch is 64MB in size.
- Spark Internal Row --> Arrow conversion to use this mechanism (relevant for caching)
- `VeAmplifyBatchesPlan` to apply a similar approach. This to use `BatchAmplifier` which is a generic way to transform an iterator to an iterator of batches that get as close to a target limit as possible.
- Add `SparkInternalRowsToArrowColumnarBatchesTest` test to validate the spark converter just in case.
> Amplify batches

- src/main/resources/com/nec/cyclone/cpp/Makefile
If we don't use the same aggressive optimizations and inlining used in Frovedis the performance will suffer due to us being very loose with the code we use and generate.  We want the compiler to do as much of the work as possible for us.
> Restore the optimized flags used in Frovedis in Makefile

- src/main/scala/com/nec/spark/LocalVeoExtension.scala
- src/main/scala/com/nec/spark/agile/CExpressionEvaluation.scala
- src/main/scala/com/nec/spark/agile/CodeStructure.scala
- src/main/scala/com/nec/spark/planning/CombinedCompilationColumnarRule.scala
- src/test/scala/com/nec/cmake/functions/CombineSourcesSpec.scala
Combine multiple sources together into a single source file, to simplify compilation steps required from many to just 1.
We parse each source file to figure out the headers followed by main code; then deduplicate headers and rejoin into a single file.
We can simplify/remove this code as part of a bigger step where we extract a lot of common/repeated functions into the general library.
Test evidence (no regression down from `main`):
https://www.sparkcyclone.io/tpc-html/20220131040527/
> Compile all the codes in 1 file

- .gitignore
- build.sbt
- src/main/resources/com/nec/cyclone/cpp/Makefile
- src/main/resources/com/nec/cyclone/cpp/cyclone.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone.hpp
- src/main/resources/com/nec/cyclone/cpp/test.cpp
- src/main/scala/com/nec/spark/agile/CExpressionEvaluation.scala
- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/StringHole.scala
- src/main/scala/com/nec/spark/agile/StringProducer.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
- src/main/scala/com/nec/ve/VeKernelCompiler.scala
- src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala
- src/test/scala/com/nec/cmake/functions/WordsCheckSpec.scala
- src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
This is part of the ongoing work to restore correctness of behavior with the replacement of the imperative strings implementation of copy with the Frovedis counterpart.  This was initially part of the efforts to address Query 21 failures (see https://github.com/XpressAI/SparkCyclone/pull/442)
Summary:
1. The Cyclone library could not be built locally to test out snippets of the generated C++ code on example data, which made debugging and testing out changes unnecessarily difficult.
2. The generated code for Frovedis words copying across group-by bucketing operations was incorrect even though it compiled.  It was performing chars and lens assignments incorrectly, which resulted in garbage output upon calling `frovedis::concat_words()`.
3. The generated code for the group-by bucketing …
> Fix the code generation for `GroupingFunction.groupData()`

- src/main/resources/com/nec/cyclone/cpp/test.cpp
- src/main/scala/com/nec/spark/agile/CExpressionEvaluation.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
- src/main/scala/com/nec/ve/MergerFunction.scala
Summary:
1. Similar to the generated code for bucket exchanges, the existing code generation for batch merges did not preserve the validity buffer when merging `nullable_varchar_vectors`.  
2. The generated code also did not pre-allocate the arrays for the `output**` pointers being passed in prior to writing out data to them.  
3. Rewrite `MergerFunction.merge` to address issues 1 and 2
4. Add example C++ code to showcase that the generated code now works
5. Comparing the most [recent](https://www.sparkcyclone.io/tpc-html/20220131040527/) run on a PR against main vs [this branch](https://www.sparkcyclone.io/tpc-html/20220131110934/), the difference is the failures of Q7, 8, 9 (which has been the case since the start of the `eg_remove_imp_str` branch) and the passing of Q13.
Example …
> [merge] Fix code generation for batch merges

- SBT.md
- build.sbt
- src/main/scala/com/nec/spark/LocalVeoExtension.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala
- src/test/scala/com/nec/spark/BenchTestingPossibilities.scala
- src/test/scala/com/nec/spark/SparkAdditions.scala
- src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
- src/test/scala/com/nec/tpc/TPCHVESqlSpec.scala
- src/test/scala/com/nec/ve/CachingSpec.scala
- src/test/scala/com/nec/ve/DynamicVeSqlExpressionEvaluationSpec.scala
But with option to enable it.
Also, clean up `SBT.md`
E.g.:
```
because of: java.lang.RuntimeException: Could not map scalar-subquery#1647 [] (class org.apache.spark.sql.catalyst.expressions.ScalarSubquery None); input is List(l_suppkey#53L, sum((l_extendedprice * (CAST(1 AS DOUBLE) - l_discount)))#1651), condition is (isnotnull(sum((l_extendedprice * (CAST(1 AS DOUBLE) - l_discount)))#1651) AND (sum((l_extendedprice * (CAST(1 AS DOUBLE) - l_discount)))#1651 = scalar-subquery#1647 []))
java.lang.RuntimeException: Could not map scalar-subquery#1647 [] (class org.apache.spark.sql.catalyst.expressions.ScalarSubquery None); input is List(l_suppkey#53L, sum((l_extendedprice * (CAST(1 AS DOUBLE) - l_discount)))#1651), condition is (isnotnull(sum((l_extendedprice * (CAST(1 AS DOUBLE) - …
```
> Failfast off by default

- src/test/scala/com/nec/cmake/eval/InStringHoleEvaluationSpec.scala
- Limit the range of avilable delimiters for InStringHoleEvaluation from
[1, 255] to [1, 127].  While the delimiters with char value above 127
are fine in the generated C++ code, the string is being encoded as UTF-8,
and since the sign bit is set, it becomes 2 bytes, which map to 2 chars
sent to the C side.
> [stringhole] Limit the range of delimiters for InStringHoleEvaluation

- src/test/scala/com/nec/testing/ProductListEquivalenceCheck.scala
- src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
- Remove exact checks from TPC-H Q15, Q17, and Q22 so that they can pass
Addresses https://github.com/XpressAI/SparkCyclone/issues/471
> [checks] Remove exact checks

- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/groupby/GroupByOutline.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
- src/main/scala/com/nec/ve/MergerFunction.scala
- src/test/scala/com/nec/cmake/eval/LongBigIntRetrieveSpec.scala
- src/test/scala/com/nec/ve/PureVeFunctions.scala
(int*)(xxx) became static_cast<int*>(xxx).
Note that these casts are strictly not required. Casting from nullptr to another type of pointer can be done via an implicit conversion. But there is significant value in documenting what type the value is being converted into. Also, static_cast has no runtime overhead.
> Changed the old style C casts into new style C++ casts.

- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.cc
- src/main/resources/com/nec/cyclone/cpp/examples.cpp
- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/groupby/GroupByOutline.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
- src/test/scala/com/nec/cmake/eval/LongBigIntRetrieveSpec.scala
function is found in src/main/resources/com/nec/cyclone/cpp/frovedis/core/utility.hpp
We used to do an inefficient ceiling conversion that involved conversion to and from a floating point value. This function is very efficient. This is a template function, so both arguments have to be exactly the same data type. This required adding casts to the arguments.
> Added code to call the ceil_div() function

- src/main/resources/com/nec/cyclone/cpp/Makefile
- src/main/resources/com/nec/cyclone/cpp/README.md
- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/transfer-definitions.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/transfer-definitions.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/driver.cc
- src/main/resources/com/nec/cyclone/cpp/tests/example-spec.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/test-utils.cc
- src/main/resources/com/nec/cyclone/cpp/tests/test-utils.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/transfer-definitions-spec.hpp
- src/main/scala/com/nec/spark/agile/CppResource.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
Summary:
1. Redefine the nullable scalar vectors as instantiations of `NullableScalarVec<T>` for consistency of implementation
2. Implement the `clone()` and `equals()` methods for all the `nullable_T_vectors`
2. Add unit tests to check that these implementations are correct.
3. Simplify the implementation of `GroupingFunction.cloneVecStmt()` to call the C++ member functions for struct `copy()`.
See the [example](https://gist.github.com/q10/f300ee7e1f0a337f002c446c6c18a471) generated code for vastly simplfiied implementation of the exchange function for the zero key case.
The primary goal for this PR is to demonstrate that redefining the nullable scalar vectors as template instantiation of a common template class works.  Additional work will follow to fold the rest of the code generated …
> Implement `clone()` and `equals()` methods for the `nullable_T_vector` structs 

- build.sbt
- src/main/scala/com/nec/arrow/VeArrowNativeInterface.scala
- src/main/scala/com/nec/arrow/colvector/BytePointerColVector.scala
- src/main/scala/com/nec/arrow/colvector/GenericColVector.scala
- src/main/scala/com/nec/arrow/colvector/UnitColBatch.scala
- src/main/scala/com/nec/arrow/colvector/UnitColVector.scala
- src/main/scala/com/nec/spark/planning/aggregation/VeHashExchangePlan.scala
- src/main/scala/com/nec/spark/planning/plans/VectorEngineJoinPlan.scala
- src/main/scala/com/nec/ve/VeProcess.scala
- src/main/scala/com/nec/ve/VeProcessMetrics.scala
- src/main/scala/com/nec/ve/VeRDD.scala
- src/main/scala/com/nec/ve/colvector/VeColBatch.scala
- src/main/scala/com/nec/ve/colvector/VeColVector.scala
- src/main/scala/com/nec/ve/serializer/VeDeserializationStream.scala
- src/main/scala/com/nec/ve/serializer/VeSerializationStream.scala
- src/main/scala/com/nec/ve/serializer/VeSerializer.scala
- src/main/scala/com/nec/ve/serializer/VeSerializerInstance.scala
- src/main/scala/com/nec/ve/serializer/package.scala
- src/main/scala/org/apache/spark/metrics/source/ProcessExecutorMetrics.scala
- src/test/resources/logback-test.xml
- src/test/scala/com/nec/arrow/colvector/UnitColVectorSpec.scala
- src/test/scala/com/nec/ve/JoinRDDSpec.scala
- src/test/scala/com/nec/ve/VERDDSpec.scala
- src/test/scala/com/nec/ve/serializer/VeSerializerSpec.scala
- src/test/scala/org/apache/spark/sql/vectorized/DualModeTest.scala
The key concept is that we intercept/serialize only when it is needed to do (for exchange, rather than generally) so to avoid complications in dealing with unfamiliar types. That is where we therefore pass the serializer explicitly.
Query 1 and Query 2 work.
- (De-)Serialize data from VE into the Serialization Stream as closely as possible. Using `Channels`.
- Disabled by default, will need @Wosin to complete the exchange fixing task.
- Disable `TRACE`-level log in TPC tests, affects performance a lot.
Next we could look at using a custom SerializationManager for even higher performance (separate task), possibly even get VE to speak to VE across network.
---
`VectorEngine` tests give this in terms of performance:
> Could be due to slowness on joins mostly
> Use a custom Serializer for exchanges

- .github/workflows/benchmark-collector-all.yml
- .github/workflows/benchmark-collector.yml
- .github/workflows/unittests-cmake.yml
- build.sbt
- src/main/scala/com/nec/arrow/ArrowEncodingSettings.scala
- src/main/scala/com/nec/arrow/VeArrowNativeInterface.scala
- src/main/scala/com/nec/arrow/colvector/GenericColVector.scala
- src/main/scala/com/nec/arrow/colvector/UnitColVector.scala
- src/main/scala/com/nec/spark/agile/join/JoinMatcher.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/aggregation/VeHashExchangePlan.scala
- src/main/scala/com/nec/spark/planning/plans/VeAmplifyBatchesPlan.scala
- src/main/scala/com/nec/spark/planning/plans/VectorEngineJoinPlan.scala
- src/main/scala/com/nec/ve/VeProcess.scala
- src/main/scala/com/nec/ve/VeProcessMetrics.scala
- src/main/scala/com/nec/ve/VeRDD.scala
- src/main/scala/com/nec/ve/colvector/VeColBatch.scala
- src/main/scala/com/nec/ve/colvector/VeColVector.scala
- src/main/scala/com/nec/ve/serializer/VeDeserializationStream.scala
- src/main/scala/com/nec/ve/serializer/VeSerializationStream.scala
- src/main/scala/com/nec/ve/serializer/package.scala
- src/test/scala/com/nec/arrow/colvector/UnitColVectorSpec.scala
- src/test/scala/com/nec/ve/JoinRDDSpec.scala
- src/test/scala/com/nec/ve/VERDDSpec.scala
- src/test/scala/com/nec/ve/serializer/VeSerializerSpec.scala
- tpcbench-run/src/main/scala/sc/GitHubInput.scala
- tpcbench-run/src/main/scala/sc/RunBenchmarksApp.scala
Performance so far (Spark join = ~1m 30s):
Changes:
- Introduce dual-mode deserialization (seems deserializing straight from stream does not work when we do JOIN. Not clear why). Performance impact is minimal, however.
- Remove filter-on-ve configuration from GitHub action, so that it is less cluttered.
- Make CMake tests run on GH ubuntu, rather than on VH, so that the testing happens more quickly.
- Specify explicit `javaCppVersion`, to avoid dual library imports (which could yield some funny behaviors), and disable the JavaCPP SBT plugin for modules that don't need it.
- Add a header to specify how much space a serialization will take
- Extract `JoinMatcher` out of `VeRewriteStrategy`
- Use a nicer clean-up method in `VeHashExchange`
- `VeAmplifyBatches` to be more optimized (in case …
> Serialize the JOIN

- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/example.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/example.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/transfer-definitions.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/tuple_hash.hpp
- src/main/resources/com/nec/cyclone/cpp/examples.cpp
- src/main/resources/com/nec/cyclone/cpp/tests/driver.cc
- src/main/resources/com/nec/cyclone/cpp/tests/example_spec.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_scalar_vector_spec.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_varchar_vector_spec.hpp
- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/DeclarativeAggregationConverter.scala
- src/main/scala/com/nec/spark/agile/SparkExpressionToCExpression.scala
- src/main/scala/com/nec/spark/agile/StringHole.scala
- src/main/scala/com/nec/spark/agile/StringProducer.scala
- src/main/scala/com/nec/spark/agile/groupby/GroupByOutline.scala
- src/main/scala/com/nec/spark/agile/join/GenericJoiner.scala
- src/main/scala/com/nec/spark/agile/join/JoinByEquality.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
- src/main/scala/com/nec/ve/MergerFunction.scala
- src/test/scala/com/nec/cmake/eval/LongBigIntRetrieveSpec.scala
- src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala
- src/test/scala/com/nec/cmake/eval/SparkToVeAggregatorSpec.scala
- src/test/scala/com/nec/ve/ArrowTransferCheck.scala
- src/test/scala/com/nec/ve/PureVeFunctions.scala
Summary:
1. Updated the C++ code generation to use `get_validity()` and `set_validity()` member functions instead of their non-member function variants.  This paves the way for encapsulating operations on `nullable_T_vector`s, so that the C++ code generation can be simplified.
2. Move the `merge` implementation to C++ for the `nullable_T_vector` types.
3. Simplified the `MergerFunction` to use the native C++ implementation for `merge` instead of generating code
4. Fix the hash generation/bucketing inside `GroupingFunction` and simplified its associated C++ code generation
5. Reformat `GroupingFunction` as a case class instead of as a singleton method so that we can eventually work with higher level abstractions.
Generated code for `MergerFunction` has been simplified from [this …
> Simplification of `GroupingFunction` and `MergerFunction`

- src/main/scala/com/nec/spark/SparkCycloneExecutorPlugin.scala
If another Spark process is running on VE_NODE_NUMBER.  Cyclone will try the next one (up to 8) before giving up.
> Try next VE if unable to start executor procs on the VE assigned.

- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_sort.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_utils.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/transfer-definitions.hpp
- src/main/resources/com/nec/cyclone/cpp/examples.cpp
- src/main/resources/com/nec/cyclone/cpp/tests/cyclone_sort_spec.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/driver.cc
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_varchar_vector_spec.hpp
- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/CppResource.scala
- src/main/scala/com/nec/spark/agile/GroupingCodeGenerator.scala
- src/main/scala/com/nec/ve/GroupingFunction.scala
- src/test/scala/com/nec/cmake/eval/LongBigIntRetrieveSpec.scala
- src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala
Summary:
- Move generic tuple sort to the C++ level using variadic templates and template function recursion
- Update the existing nullable_T_vector `hash_at()` functions to use `int64_t`
- Implement `hash_vec()` for nullable_varchar_vector to get a vector of hash values for each value in the vector
- Implement the new C++ code into the grouping routines
> [cpp] Move sorting and hashing down to C++

- src/main/scala/com/nec/spark/LocalVeoExtension.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala
- src/main/scala/com/nec/spark/planning/hints/VeHint.scala
- src/test/scala/com/nec/cmake/DynamicCSqlExpressionEvaluationSpec.scala
Allows you to add Spark SQL hints that allow you to control the *on-ve configuration options on a per-query basis.
I.E.
```
select /*+ SORT_ON_VE(true) */ max(a) from values (1), (2), (3) as tab1(a)
```
https://github.com/XpressAI/SparkCyclone/blob/495901bf7ba1a3200ea2e41d63b724921a6096da/src/main/scala/com/nec/spark/LocalVeoExtension.scala#L56-L64
> Add VEHints to enable/disable options per-query.

- src/main/scala/com/nec/spark/LocalVeoExtension.scala
Some queries like 2, or 5 could have a lot of these redundant conversions if the right options are used.
> Remove redundant Spark-VE-Spark and VE-Spark-VE conversions.

- src/main/scala/com/nec/spark/LocalVeoExtension.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/VeFunction.scala
The huge pattern match in VERewriteStrategy makes it very hard to navigate the file. 
This refactors this and pulls the result of those case matches into their own methods.
While at it, I've also deduplicated some low hanging duplicate code warnings.
> Refactor VERewriteStrategy

- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/transfer-definitions.hpp
- src/main/resources/com/nec/cyclone/cpp/examples.cpp
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_scalar_vector_spec.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_varchar_vector_spec.hpp
- src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala
- src/main/scala/com/nec/spark/agile/groupby/GroupByOutline.scala
- src/main/scala/com/nec/spark/agile/groupby/GroupByPartialGenerator.scala
- src/main/scala/com/nec/spark/agile/join/GenericJoiner.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/ve/FilterFunction.scala
- src/main/scala/com/nec/ve/ProjectionFunction.scala
- src/test/scala/com/nec/ve/eval/RealExpressionEvaluationUtils.scala
Summary:
- Move `renderProjection()` over to a proper `ProjectionFunction` class abstraction
- Rename `nullable_T_vector::filter()` to `nullable_T_vector::select()` as the same function can be used for returning a `nullable_T_vector` of the same elements re-ordered.  Add unit tests to test this specific feature.  This will be used for the simplification of `renderSort()` in a subsequent PR
- Fix a small bug with code generation for joins, where both the left and right exchange functions have the same function name
- Run the periodic `scalafmt` cleanup
> Implement `ProjectionFunction`

- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_utils.hpp
- src/main/scala/com/nec/spark/agile/SparkExpressionToCExpression.scala
- src/test/scala/com/nec/spark/agile/FlatToNestedFunctionTest.scala
Fixes "Vectorization obstructive function reference.: max/min" messages.
> Replace std::max and std::min with MIN/MAX macros.

- rddbench/src/main/scala/RDDBench.scala
- src/main/scala/com/nec/native/CppTranspiler.scala
- src/main/scala/com/nec/util/DateTimeOps.scala
- src/main/scala/com/nec/ve/VeRDD.scala
- src/test/scala/com/nec/native/CppTranspilerSpec.scala
Summary:
- Add basic support to the transpiler for parsing `java.time.Instant`s and supporting `compareTo` between two `Instant`s.  This does NOT support transpilation of more advanced features such as calling on methods of `Instant` to extract the epoch milliseconds for example.
- Add support for converting `RDD[Instant]` to `VeRDD[Instant]`
- Update the existing transpiler unit tests to pass
- Add example benchmark query to test `RDD[Instant]`
- Clean up the existing benchmark code
> Very basic support for `RDD[Instant]`

- src/main/scala/com/nec/native/CppTranspiler.scala
- src/main/scala/com/nec/util/SyntaxTreeOps.scala
- Convert the `Expr[T => U]` into a typed tree before evaluation, and use
their type values to determine the `CFunction2` input and output vectors.
Previously, the transpilation was limited to generating T => T transformations.
> [transpile] Use typed trees for `evalFunc`

- rddbench/src/main/scala/RDDBench.scala
- src/main/scala/com/nec/ve/FilteredVeRDD.scala
- src/main/scala/com/nec/ve/MappedVeRDD.scala
- src/main/scala/com/nec/ve/VeConcatGroups.scala
- src/main/scala/com/nec/ve/VeConcatRDD.scala
- src/main/scala/com/nec/ve/VeGroupByRDD.scala
- src/main/scala/com/nec/ve/VeRDD.scala
- src/main/scala/com/nec/ve/colvector/VeColBatch.scala
At the interface level we pretend to work on tuples. This in turn means that we need to turn the column vectors back into tuples when we go from VeRDD to regular RDD based execution.
Unfortunately, ClassTag doesn't appear to hold the necessary information for us to know exactly what types are necessary for the tuple conversion. For this reason we move to using TypeTag instead of ClassTag where ever possible.
> Add support for VeColBatch to Tuple conversion

- src/main/scala/com/nec/native/CompilerToolBox.scala
- src/main/scala/com/nec/native/CppTranspiler.scala
- src/main/scala/com/nec/native/FunctionReformatter.scala
- src/main/scala/com/nec/native/FunctionTyping.scala
- src/main/scala/com/nec/ve/VeRDD.scala
The toolbox is somewhat stateful. Depending on the very first expression it
typechecks, some fundamental types (e.g. Int, Long, etc.) will either be
comparable with =:= or not.
For this reason we make one single primed toolbox available for use
everywhere.
This fixes weird issues like reported in https://github.com/XpressAI/SparkCyclone/pull/548#issuecomment-1086913663
or like this:
```
java.lang.AssertionError: assertion failed: ofEpochSecond value ofEpochSecond <none>
[info]   at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
[info]   at scala.reflect.internal.Importers$StandardImporter.$anonfun$importSymbol$6(Importers.scala:208)
[info]   at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:205)
[info]   at …
```
> Prime Compiler ToolBox on Creation

- src/main/scala/com/nec/native/CompilerToolBox.scala
- src/main/scala/com/nec/native/CppTranspiler.scala
- src/main/scala/com/nec/native/FunctionReformatter.scala
- src/main/scala/com/nec/native/FunctionTyping.scala
- src/main/scala/com/nec/native/SyntaxTreeOps.scala
- src/main/scala/com/nec/ve/VeRDD.scala
- src/test/scala/com/nec/native/CppTranspilerSpec.scala
- src/test/scala/com/nec/native/FunctionReformatterUnitSpec.scala
- src/test/scala/com/nec/util/FixedBitSetUnitSpec.scala
- Add `FunctionReformatter` to rewrite an expression tree for a Function
to expand out the tuples in the function parameters, and return a type-checked
expression tree.  This will help facilitate code generation for `MappedVeRDD`
that have functions that take in `Tuple`s of primitive types
- Add unit test for the feature
> [transpiler] Rewrite Map functions to expand `Tuple` parameters

- src/main/scala/com/nec/cache/ColumnarBatchToVeColBatch.scala
- src/main/scala/com/nec/cache/DualColumnarBatchContainer.scala
- src/main/scala/com/nec/cache/InVectorEngineCacheSerializer.scala
- src/main/scala/com/nec/colvector/ByteArrayColVector.scala
- src/main/scala/com/nec/colvector/BytePointerColVector.scala
- src/main/scala/com/nec/colvector/UnitColBatch.scala
- src/main/scala/com/nec/colvector/UnitColVector.scala
- src/main/scala/com/nec/colvector/VeColBatch.scala
- src/main/scala/com/nec/colvector/VeColVector.scala
- src/main/scala/com/nec/spark/SparkCycloneExecutorPlugin.scala
- src/main/scala/com/nec/ve/VeAsyncResult.scala
- src/main/scala/com/nec/ve/VeProcess.scala
- src/main/scala/org/apache/spark/metrics/source/ProcessExecutorMetrics.scala
- src/test/scala/com/nec/colvector/UnitColVectorUnitSpec.scala
- src/test/scala/com/nec/colvector/VeColVectorUnitSpec.scala
- src/test/scala/com/nec/ve/DualModeVESpec.scala
- src/test/scala/com/nec/ve/DynamicBenchmarkVeCheck.scala
- src/test/scala/com/nec/ve/DynamicVeSqlExpressionEvaluationSpec.scala
- src/test/scala/com/nec/ve/WithVeProcess.scala
With `VEO_LOG_DEBUG=1`, we can see that we have many small reads and writes to/from the VE. This can introduce a lot of latency.
This PR changes the communication patterns in such a way, that asynchronous reads/writes are used wherever possible. By waiting for the responses only after all requests have been sent, we can hide a lot of that latency.
There is one pattern that may look a bit weird in this PR `.map(_.apply()).map(_.get())`. It exists for one very specific purpose:
In order to make it possible to transfer entire partitions to the VE in an asynchronous fashion, we need to be able to do that in a staged manner.
First the memory for all the transfers gets allocated - this is async below the covers, but that isn't exposed in aveo to us. As far as I can tell, this will only finish …
> Use asynchronous memory access

- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_scalar_vector_spec.cc
- src/main/resources/com/nec/cyclone/cpp/tests/nullable_varchar_vector_spec.cc
When switching to external resource management, we've missed updating the short circuit logic for handling the "everything will end up in its own group anyway"-case.
That resulted in a weird edge case where sometimes things would crash because the pointers of two memory regions would converge and freeing the temporary memory region would result in also freeing the result memory.
> Bugfix: Memcpy on shortcircuit

- src/main/scala/com/nec/colvector/VeColBatch.scala
`bytePointer.asBuffer()` will create a buffer with capacity=1 for empty buffers, and therefore write something (= 1 byte) to the channel, even though we don't want it to write anything in that case.
> Add guard to only write non-zero buffers

- src/main/scala/com/nec/util/CallContext.scala
- src/main/scala/com/nec/vectorengine/DeferredVeProcess.scala
- src/main/scala/com/nec/vectorengine/VeProcessImpl.scala
- src/main/scala/com/nec/vectorengine/VeProcessTraits.scala
- src/test/scala/com/nec/cache/ColumnarBatchToVeColBatchTest.scala
- src/test/scala/com/nec/colvector/InputSamples.scala
- src/test/scala/com/nec/vectorengine/VeProcessUnitSpec.scala
This PR only introduces the new `VeProcess` implementation.  More work will be done in subsequent PRs before integration with the rest of the codebase can commence.
Summary:
- Introduce a new implementation of `VeProcess` that is a simpler and stronger abstraction than the existing implementation
- Implement `CallContext` to eventually replace the `OriginalCallingContext` class that is nested in the old `VeProcess`
- Add algebraic data types to abstract over the creation and handling of the VE process call args stack
- Add models to abstract over library references and library symbols loaded by the VE process
- Add methods to abstract out the creation of the VE process and VEO thread contexts
- Add `VeAsyncReqId` model to abstract over async request IDs
- Add unit tests for the …
> [NS-38] New `VeProcess` implementation

- src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.hpp
- src/main/resources/com/nec/cyclone/cpp/tests/packed_transfer_spec.cc
- src/main/scala/com/nec/cache/TransferDescriptor.scala
- src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala
- src/main/scala/com/nec/spark/planning/plans/SparkToVectorEnginePlan.scala
- src/test/scala/com/nec/colvector/PackedTransferSpec.scala
There are two bugs fixed here:
* Alignment related garbage copying when data was coming from the JVM
* Unexpected behavior when collecting a partition iterator into a list instead of working directly off the iterator and collecting the results afterwards. 
As part of the debugging process additional tests for transfers from the JVM were added. This has highlighted a difference in default values for unused validity buffer bits. For this reason the usage of "append_bitsets" has been disabled until it is adapted for the same defaults.
> Bugfix: Handle alignment correctly

- src/main/scala/com/nec/vectorengine/DeferredVeProcess.scala
- src/main/scala/com/nec/vectorengine/VeProcessImpl.scala
- src/main/scala/com/nec/vectorengine/VeProcessTraits.scala
- src/main/scala/com/nec/vectorengine/VectorEngineImpl.scala
- src/main/scala/com/nec/vectorengine/VectorEngineTraits.scala
- src/test/scala/com/nec/colvector/InputSamples.scala
- src/test/scala/com/nec/vectorengine/VeProcessUnitSpec.scala
- src/test/scala/com/nec/vectorengine/VectorEngineFunSpec.scala
- src/test/scala/com/nec/vectorengine/WithVeProcess.scala
Summary:
- Hook up metrics for memory allocations, de-allocations, and sync calls to `MetricRegistry`
- Add both gauge and timer metrics for better observability
- Add unit tests for the integration of metrics to the new `VeProcess` and `VectorEngine` implementations
- Add support for loading `libcyclone.so` using `WithVeProcess`
> [NS-41][metrics] Add metrics to the new `VeProcess` and `VectorEngine` implementations

- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_utils.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.cc
- src/main/resources/com/nec/cyclone/cpp/tests/cyclone_utils_spec.cc
- src/main/scala/com/nec/colvector/ArrayTConversions.scala
- src/test/scala/com/nec/colvector/ArrayTConversionsUnitSpec.scala
The problem in NS-49 was that the packed transfer spec failed because during transfer only the bits for existing elements are considered when merging data into the validity buffer. padding bits are kept at 0. 
However, the default validity buffer created when converting an Array of scalars into a BytePointerColVector would be set to "all valid" even for the padding bits.
This created a discrepancy after a round trip VH->VE->VH.
In this PR I've adapted the conversion code to adopt the "padding bits are 0" default.
Something appears to be still wrong :/ the TPCH tests fail with just slightly wrong results.
> Re-enable append_bitsets

- src/main/scala/com/nec/cache/TransferDescriptor.scala
- src/main/scala/com/nec/colvector/ArrayTConversions.scala
- src/main/scala/com/nec/colvector/ArrowVectorConversions.scala
- src/main/scala/com/nec/colvector/SeqOptTConversions.scala
- src/main/scala/com/nec/colvector/VeColBatch.scala
- src/main/scala/com/nec/spark/agile/CppResource.scala
- src/main/scala/com/nec/vectorengine/DeferredVeProcess.scala
- src/main/scala/com/nec/vectorengine/LibCyclone.scala
- src/main/scala/com/nec/vectorengine/VeProcessImpl.scala
- src/main/scala/com/nec/vectorengine/VeProcessTraits.scala
- src/main/scala/com/nec/vectorengine/VectorEngineImpl.scala
- src/main/scala/com/nec/vectorengine/VectorEngineTraits.scala
- src/test/scala/com/nec/colvector/ArrayTConversionsUnitSpec.scala
- src/test/scala/com/nec/colvector/PackedTransferSpec.scala
- src/test/scala/com/nec/colvector/SeqOptTConversionsUnitSpec.scala
- src/test/scala/com/nec/vectorengine/VeProcessUnitSpec.scala
- src/test/scala/com/nec/vectorengine/VectorEngineFunSpec.scala
- src/test/scala/com/nec/vectorengine/WithVeProcess.scala
Summary:
- Port the `TransferDescriptor`-based data transfer feature over from the old `VeProcess` to the new `VectorEngine` implementation
- Add histogram-based metrics to the new `VeProcess` implementation
- Add support for registering and unregistering memory allocations, which is useful for tracking memory allocations made on the VE side during function calls
- Add functional tests for `TransferDescriptor`-based data transfer support in the new `VectorEngine` implementation
- Add `LibCyclone` object to hold souce of truth information about `libcyclone.so`
- Add test cases with concrete example inputs to highlight failing test cases with `TransferDescriptor`-based bulk data transfer
- Update existing `BytePointerColVector` conversion tests to be more strict with verifying the content …
> [NS-37] Integrate partition level transfer into the new `VectorEngine` implementation

- build.sbt
- rddbench/run_rddbench.sh
- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_utils.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.cc
- src/main/resources/com/nec/cyclone/cpp/tests/cyclone_utils_spec.cc
- src/main/resources/com/nec/cyclone/cpp/tests/packed_transfer_spec.cc
- src/main/scala/com/nec/cache/TransferDescriptor.scala
- src/main/scala/com/nec/colvector/SeqOptTConversions.scala
- src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
- src/main/scala/com/nec/spark/planning/VeColumnarRule.scala
- src/main/scala/com/nec/spark/planning/plans/SparkToVectorEnginePlan.scala
- src/test/scala/com/nec/colvector/PackedTransferSpec.scala
This also includes some initial property based tests. However, I've noticed that it can find cases which will crash the JVM *sometimes*.  For this reason they are set to be ignored for now.
> Bugfixes: Calculate validity buffer steps based on processed elements & fix sort order issues

- .github/workflows/unittests.yml
Run on our actions runner as it has cached versions of javacpp-presets
> Update JVM unit tests

- src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_utils.hpp
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.cc
From #584, which unfortunately started from an unclean state:
Fix for NS-44 (Replace bitwise merge with vectorized merge):
nullable_scalar_vector and nullable_varchar_vector now use cyclone_utils::fast_validity_merge for vectorized merge of validity bits.
I'd love to know, if it's any faster now...
> [NS-44] Vectorize Merge

- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc
Cherry-picks a nullptr copy bugfix from https://github.com/XpressAI/SparkCyclone/pull/592
> Hotfix: group by short circuit bug

- src/main/scala/com/nec/cache/BpcvTransferDescriptor.scala
- src/main/scala/com/nec/cache/RowCollectingTransferDescriptor.scala
- src/main/scala/com/nec/cache/TransferDescriptor.scala
- src/main/scala/com/nec/spark/planning/plans/SparkToVectorEnginePlan.scala
- src/main/scala/com/nec/util/FixedBitSet.scala
- src/main/scala/com/nec/vectorengine/VectorEngineImpl.scala
- src/main/scala/com/nec/vectorengine/VectorEngineTraits.scala
- src/test/scala/com/nec/cache/RowCollectingTransferDescriptorUnitSpec.scala
- src/test/scala/com/nec/cache/TransferDescriptorUnitSpec.scala
- src/test/scala/com/nec/colvector/PackedTransferSpec.scala
- src/test/scala/com/nec/vectorengine/VectorEngineFunSpec.scala
Part of https://github.com/XpressAI/SparkCyclone/pull/595 which only provides the custom replacement for Spark's RowToColumnar
> Use this config option to set how many rows should be accumulated before transferring them as a batch to the VE: spark.com.nec.spark.ve.columnBatchSize
If it isn't set, it will default to the value of spark.sql.inMemoryColumnarStorage.batchSize, which itself defaults to 10000.
> You probably want a higher value; 64000 is probably a good starting point. The optimal value will depend on the actual workload. This is also something that we may want to revisit, and try to come up with a more adaptive way of configuring this.
> Implement custom replacement for Spark's RowToColumnar

- src/main/resources/io/sparkcyclone/cpp/benchmarks/cyclone_scalar_grouping_benchmark.cc
- src/main/resources/io/sparkcyclone/cpp/benchmarks/cyclone_string_grouping_benchmark.cc
- src/main/resources/io/sparkcyclone/cpp/benchmarks/nanobench.h
- src/main/resources/io/sparkcyclone/cpp/cyclone/cyclone.hpp
- src/main/resources/io/sparkcyclone/cpp/cyclone/cyclone_grouping.hpp
- src/main/resources/io/sparkcyclone/cpp/cyclone/cyclone_utils.hpp
- src/main/resources/io/sparkcyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/io/sparkcyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/io/sparkcyclone/cpp/cyclone/packed_transfer.cc
- src/main/resources/io/sparkcyclone/cpp/cyclone/transfer-definitions.hpp
- src/main/resources/io/sparkcyclone/cpp/examples.cpp
- src/main/resources/io/sparkcyclone/cpp/tests/cyclone_grouping_spec.cc
- src/main/resources/io/sparkcyclone/cpp/tests/cyclone_utils_spec.cc
- src/main/resources/io/sparkcyclone/cpp/tests/nullable_scalar_vector_spec.cc
- src/main/resources/io/sparkcyclone/cpp/tests/nullable_varchar_vector_spec.cc
- src/main/scala/io/sparkcyclone/native/transpiler/CppTranspiler.scala
Summary:
- Patch the included `nanobench` library be able to compile under `nc++`
- Add more comments to the existing grouping code so that it is easier to understand
- Experiment with an implementation of `multiple_radix_sort_and_group` for grouping string vectors
- Add benchmark code scaffold for grouping strings
- Implement `sort_and_group_multiple()`, which takes a set of multiple contiguous ranges, applies sort + grouping to each subset, and combines the output group delimiters for each subset into a single array
- Re-implement the `sort_and_group_multiple()` function to be much more efficient and use raw C pointers instead of C++ data structures
- Implement a new version of `nullable_varchar_vector::group_indexes_on_subset()` that groups elements without hashing, and uses …
> [NS-69] Vectorized grouping for `nullable_varchar_vector`

- src/main/resources/io/sparkcyclone/cpp/cyclone/nullable_scalar_vector.cc
- src/main/resources/io/sparkcyclone/cpp/cyclone/nullable_varchar_vector.cc
- src/main/resources/io/sparkcyclone/cpp/cyclone/transfer-definitions.hpp
- src/main/resources/io/sparkcyclone/cpp/examples.cpp
- src/main/resources/io/sparkcyclone/cpp/tests/nullable_scalar_vector_spec.cc
- src/main/resources/io/sparkcyclone/cpp/tests/nullable_varchar_vector_spec.cc
- src/main/scala/io/sparkcyclone/spark/codegen/groupby/GroupByPartialGenerator.scala
- src/test/scala/io/sparkcyclone/spark/codegen/groupby/GroupByPartialSpec.scala
Summary:
- Re-enable string vector aggregations
- Implement computing batch placement per group for strings
- Fix implementation of group indices assignment for batching
- Fix some broken code and add missing index
- Fix wrong index variable in projections
- Fix temporary buffer size to be `range_size + 1` to account for scenario where `nullable_varchar_vector::group_indexes_on_subset()` is invoked with a single subset and where every element ends up in its own group
- Add more unit tests for `nullable_varchar_vector::group_indexes_on_subset()` to cover the case where only one subset is passed in for grouping and each element ends up being in its own group
- Add better documentation for `NullableScalarVec<T>::group_indexes_on_subset()`
- Add unit test for …
> [NS-50] Re-enable Aggregation Support for rows with String columns
