SBT.md, src/test/scala/com/nec/ve/VeTracerTest.scala
Would fix the error in the CI if we also ran the tracer there.
=> Add profile target to VeTracerTest

.github/workflows/tpc.yml, src/main/scala/com/nec/spark/LocalVeoExtension.scala, src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala, src/main/scala/com/nec/spark/agile/StringProducer.scala, src/main/scala/com/nec/spark/planning/OneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, src/test/scala/com/nec/cmake/DynamicCSqlExpressionEvaluationSpec.scala, src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala, src/test/scala/com/nec/cmake/functions/WordsCheckSpec.scala
It works mostly correctly. There are some non-implemented things.
https://www.sparkcyclone.io/tpc-html/20211123160932/
Out of the issues, 2 of these are issues with the test/rounding (#352); the other 5 are to do with string projection (#350, #351) missing.
=> Project on VE

.github/workflows/tpcc.yml, src/main/resources/com/nec/arrow/functions/cpp/transfer-definitions.hpp, src/main/scala/com/nec/spark/LocalVeoExtension.scala, src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala, src/main/scala/com/nec/spark/agile/SparkExpressionToCExpression.scala, src/main/scala/com/nec/spark/agile/StringHole.scala, src/main/scala/com/nec/spark/planning/NativeAggregationEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/NativeSortEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/OneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/RowToArrowColumnarPlan.scala, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, src/main/scala/com/nec/ve/VeKernelCompiler.scala, src/test/scala/com/nec/cmake/DynamicCSqlExpressionEvaluationSpec.scala, src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala, src/test/scala/com/nec/cmake/eval/StaticTypingTestAdditions.scala, src/test/scala/com/nec/cmake/eval/StringHoleEvaluationSpec.scala, src/test/scala/com/nec/cmake/functions/WordsCheckSpec.scala, src/test/scala/com/nec/tpc/Lineitem.scala, src/test/scala/com/nec/tpc/Order.scala, src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
=> Filter plan

src/main/scala/com/nec/spark/LocalVeoExtension.scala, src/main/scala/com/nec/spark/planning/VeColumnarRule.scala, src/test/scala/com/nec/cmake/DynamicCSqlExpressionEvaluationSpec.scala, src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
Columnar transformation to remove unnecessary transfers ve <-> host.
=> D columnar

.github/workflows/benchmark.yml, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala, src/main/scala/com/nec/spark/planning/aggregation/VeHashExchange.scala, src/main/scala/com/nec/ve/VeColBatch.scala, src/main/scala/com/nec/ve/VeProcess.scala
It seems to be crashing due to this.
=> Validate VE vectors and disable the VE exchange

src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala, src/main/scala/com/nec/spark/planning/aggregation/VeHashExchange.scala, src/main/scala/com/nec/ve/VeColBatch.scala, src/main/scala/com/nec/ve/VeProcess.scala, src/main/scala/com/nec/ve/VeRDD.scala, src/test/scala/com/nec/spark/SparkAdditions.scala, src/test/scala/com/nec/ve/DetectVectorEngineSpec.scala, src/test/scala/com/nec/ve/RDDSpec.scala, tests/tpchbench/run_ve.sh, tests/tpchbench/src/main/scala/sparkcyclone/tpch/TPCHBenchmark.scala
Fails in Q2 however, but that could be for some different but related reason:
=> Fix exchange crash in Query 1

src/main/scala/com/nec/cmake/ScalaTcpDebug.scala, src/main/scala/com/nec/cmake/Spanner.scala, src/main/scala/com/nec/native/NativeCompiler.scala, src/main/scala/com/nec/spark/SparkCycloneDriverPlugin.scala, src/main/scala/com/nec/spark/SparkCycloneExecutorPlugin.scala, src/main/scala/com/nec/spark/planning/OneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/ParallelCompilationColumnarRule.scala, src/main/scala/com/nec/spark/planning/Tracer.scala, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, src/main/scala/com/nec/spark/planning/VeColBatchConverters.scala, src/main/scala/com/nec/spark/planning/VeColumnarRule.scala, src/main/scala/com/nec/spark/planning/plans/SparkToVectorEnginePlan.scala, src/main/scala/com/nec/spark/planning/plans/VeFetchFromCachePlan.scala, src/main/scala/com/nec/spark/planning/plans/VeFinalAggregate.scala, src/main/scala/com/nec/spark/planning/plans/VeFlattenPartition.scala, src/main/scala/com/nec/spark/planning/plans/VeHashExchange.scala, src/main/scala/com/nec/spark/planning/plans/VePartialAggregate.scala, src/main/scala/com/nec/spark/planning/plans/VectorEngineToSparkPlan.scala, src/main/scala/com/nec/ve/VeKernelCompiler.scala, src/main/scala/com/nec/ve/VeProcess.scala, src/main/scala/com/nec/ve/VeRDD.scala, src/main/scala/org/apache/spark/sql/vectorized/DualMode.scala, src/test/scala/com/nec/cmake/TracerTest.scala, src/test/scala/com/nec/spark/planning/JoinPlanSpec.scala, src/test/scala/org/apache/spark/sql/vectorized/DualModeTest.scala
Also, fix permission issues when creating directory structures on YARN, and remove redundant compilation.
=> Refactor/tidy up of plan structure, bring Tracing into the new plans

src/main/scala/com/nec/spark/planning/OneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/ProjectEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/SupportsVeColBatch.scala, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, src/main/scala/com/nec/ve/VeColBatch.scala, src/test/scala/com/nec/spark/planning/ProjectEvaluationPlanSpec.scala
Still in progress. Need to figure out how to prevent columns from getting cleaned and why the results are not correct.
=> Skip identity operations in OneStagePlan.

.github/workflows/benchmark-collector.yml, build.sbt, src/main/scala/com/nec/native/NativeCompiler.scala, src/main/scala/com/nec/spark/SparkCycloneDriverPlugin.scala, src/main/scala/com/nec/spark/planning/OneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/ParallelCompilationColumnarRule.scala, src/main/scala/com/nec/ve/VeKernelCompiler.scala, tpcbench-run/src/main/scala/sc/RunBenchmarksApp.scala, tpcbench-run/src/main/scala/sc/RunOptions.scala
So that we have a consistent way of saving results for reference.
=> Enable collecting-benchmark running on GitHub Actions

tpcbench-run/README.md, tpcbench-run/src/main/scala/sc/ResultsInfo.scala, tpcbench-run/src/main/scala/sc/RunBenchmarksApp.scala, tpcbench-run/src/main/scala/sc/RunDatabase.scala, tpcbench-run/src/main/scala/sc/RunOptions.scala, tpcbench-run/src/main/scala/sc/RunResult.scala, tpcbench-run/src/test/scala/sc/ResultsInfoTest.scala, tpcbench-run/src/test/scala/sc/TpcBenchSpec.scala
- Docs had a small error
- Sort columns in some order
- Save logs (stderr & stdout) & show a modal for Logs
- Enable linking to specific runs
=> Improve tpcbench-runner

.github/workflows/benchmark-collector.yml, build.sbt, tpcbench-run/README.md, tpcbench-run/src/main/scala/sc/GitHubInput.scala, tpcbench-run/src/main/scala/sc/ResultsInfo.scala, tpcbench-run/src/main/scala/sc/RunBenchmarksApp.scala, tpcbench-run/src/main/scala/sc/RunOptions.scala, tpcbench-run/src/test/scala/sc/GithubActionRewriterSpec.scala, tpcbench-run/src/test/scala/sc/OptionRewriterSpec.scala
=> Lift options into the GitHub action

.github/workflows/benchmark-collector-all.yml, build.sbt, tpcbench-run/src/test/scala/sc/GithubActionRewriterSpec.scala
So that we have continuous feedback into our reporter as well as can track things more easily
=> Create an All-Query runner that lifts out Query numbers into GitHub Actions

src/main/resources/com/nec/arrow/functions/cpp/frovedis/text/datetime_to_words.cc, src/main/resources/com/nec/arrow/functions/cpp/frovedis/text/datetime_to_words.hpp, src/main/resources/com/nec/arrow/functions/cpp/frovedis/text/float_to_words.cc, src/main/resources/com/nec/arrow/functions/cpp/frovedis/text/float_to_words.hpp, src/main/resources/com/nec/arrow/functions/cpp/frovedis/text/int_to_words.cc, src/main/resources/com/nec/arrow/functions/cpp/frovedis/text/int_to_words.hpp
(Based on #388 - doing this to reduce the size of the `eg_words` PR)
=> Import words from Frovedis

src/main/scala/com/nec/spark/SparkCycloneDriverPlugin.scala, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, tests/tpchbench/src/main/scala/sparkcyclone/tpch/TPCHBenchmark.scala, tpcbench-run/src/main/scala/sc/ResultsInfo.scala
`InMemoryRelation` is not being picked up in the translation process after a failure in plan transformation. Capture specific Filter+InMemory combination when such a failure happens.
=> Fix serializer bug

src/main/scala/com/nec/spark/SparkCycloneExecutorPlugin.scala, src/main/scala/com/nec/spark/planning/OneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/ProjectEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/SupportsVeColBatch.scala, src/main/scala/com/nec/spark/planning/VeCachedBatchSerializer.scala, src/main/scala/com/nec/spark/planning/VeColBatchConverters.scala, src/main/scala/com/nec/spark/planning/aggregation/VeFinalAggregate.scala, src/main/scala/com/nec/spark/planning/aggregation/VeFlattenPartition.scala, src/main/scala/com/nec/spark/planning/aggregation/VeHashExchange.scala, src/main/scala/com/nec/spark/planning/aggregation/VePartialAggregate.scala, src/main/scala/com/nec/spark/planning/plans/VeFinalAggregate.scala, src/main/scala/com/nec/spark/planning/plans/VeFlattenPartition.scala, src/main/scala/com/nec/spark/planning/plans/VeHashExchange.scala, src/main/scala/com/nec/spark/planning/plans/VePartialAggregate.scala, src/main/scala/com/nec/ve/VeColBatch.scala, src/main/scala/com/nec/ve/VeProcess.scala, src/main/scala/com/nec/ve/VeRDD.scala, src/test/scala/com/nec/spark/planning/ProjectEvaluationPlanSpec.scala, src/test/scala/com/nec/ve/ArrowTransferCheck.scala, src/test/scala/com/nec/ve/RDDSpec.scala, src/test/scala/org/apache/spark/sql/vectorized/DualModeTest.scala
This will enable us to identify in more detail what is going on.
@Wosin 's theory was right.
=> Change the approach of verifying the source

.github/workflows/main.yml, src/test/scala/com/nec/ve/WithVeProcess.scala, tests/tpchbench/build.sbt
So that we never miss the basics.
@Wosin @wmeddie if you want tests to be ran on your pushes, simply do `git push origin HEAD:cit/<sub-branch>`.
=> Run unit tests on specific branches

src/main/scala/com/nec/spark/agile/StringHole.scala, src/test/scala/com/nec/cmake/eval/InStringHoleEvaluationSpec.scala
- Add scope to the C++ code generation for IN string queries to avoid
name clashing when compiling the gnerated code
=> [tpch-q19] Fix code generation for IN string queries

src/test/scala/com/nec/cmake/eval/RealExpressionEvaluationSpec.scala
Change was lost due to a merge.
=> Fix compilation issue in JoinByString

README.md, src/main/scala/com/nec/arrow/ArrowEncodingSettings.scala, src/main/scala/com/nec/cache/SparkInternalRowsToArrowColumnarBatches.scala, src/main/scala/com/nec/util/BatchAmplifier.scala, src/test/scala/com/nec/util/BatchAmplifierSpec.scala
- Use Mb measurement by default
- Document all the Cyclone options
=> Improve BatchAmplifier & docs

src/test/scala/com/nec/testing/ProductListEquivalenceCheck.scala, src/test/scala/com/nec/tpc/TPCHSqlCSpec.scala
This matcher should provide better error reporting than currrent one when using custom product comparison.
=> Custom matcher to provide better errors.

src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala
This is to fix queries #4, #5, #6, #10, #21
=> Disable exchange-on-ve by default

src/main/scala/com/nec/spark/agile/SparkExpressionToCExpression.scala
By passing through the isNotNull code
Evidence:
=> Fix Query 7, 8, 9

src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala
=> Fix Query 16: exclude Distinct queries

.github/workflows/build-cyclone-release.yml, build.sbt
First official release 0.9.0 which supports all of TPC-H with on-device data re-use via VERDD.
=> Prepare for first release.

src/main/scala/com/nec/spark/agile/CFunctionGeneration.scala, src/main/scala/com/nec/spark/agile/groupby/GroupByOutline.scala, src/main/scala/com/nec/ve/GroupingFunction.scala, src/test/scala/com/nec/cmake/eval/LongBigIntRetrieveSpec.scala
also clean up int->float->int allocation expression
=> change malloc to calloc in validityBuffer allocations

src/main/scala/com/nec/spark/planning/VeRewriteStrategyOptions.scala, src/main/scala/com/nec/ve/GroupingFunction.scala
This is ridicolously small fix that was very hard to nail down.
=> D exchange fix

src/main/resources/com/nec/cyclone/cpp/frovedis/core/conditions_for_find.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/core/find_condition.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/dataframe/join.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/char_int_conv.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/text/datetime_utility.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/find.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/text/parsefloat.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/parseint.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/words.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/text/words.hpp
Includes a couple of bug fixes in joins and parsing.  Also adds a vectorized utf-8 to utf-32 conversion that we might want to use.
=> Update frovedis code to the latest master.

docs/Continuous Integration.md, docs/Cyclone Spark Plans.md, docs/Expression Evaluation.md, docs/Flow.md, docs/VeColVector and VeProcess.md, src/main/resources/com/nec/cyclone/cpp/cyclone/nullable_varchar_vector.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/core/conditions_for_find.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/core/find_condition.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/dataframe/join.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/char_int_conv.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/text/datetime_utility.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/find.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/text/parsefloat.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/parseint.hpp, src/main/resources/com/nec/cyclone/cpp/frovedis/text/words.cc, src/main/resources/com/nec/cyclone/cpp/frovedis/text/words.hpp
I used count instead of src.size() at line 50,57,58,64,65,70,72 in nullable_varchar_vector.cc
It seems to clear below error
[error] nc++: vec( 103): cyclone/nullable_varchar_vector.cc, line 50: Unvectorized loop.
I doubt this operation is good or not.
I would like to check this operation.
=> use count in nullable_varchar_vector

src/main/resources/com/nec/cyclone/cpp/examples.cpp, src/main/scala/com/nec/native/CppTranspiler.scala, src/main/scala/com/nec/native/SyntaxTreeMatchers.scala, src/test/scala/com/nec/native/TranspileMapUnitSpec.scala
Summary:
- Add support for transpiling `While` code
- Add support for transpiling `DoWhile` code
- Add support for `IfOnlyStatement`, i.e. if-statements that don't have an else clause
=> [transpiler] Add support for `While`, `DoWhile`, and `IfOnlyStatement`

src/main/scala/com/nec/spark/planning/PlanMetrics.scala, src/main/scala/com/nec/spark/planning/aggregation/VeFlattenPartition.scala, src/main/scala/com/nec/spark/planning/aggregation/VeHashExchangePlan.scala, src/main/scala/com/nec/spark/planning/plans/SparkToVectorEnginePlan.scala, src/main/scala/com/nec/spark/planning/plans/VeAmplifyBatchesPlan.scala, src/main/scala/com/nec/spark/planning/plans/VeFetchFromCachePlan.scala, src/main/scala/com/nec/spark/planning/plans/VeFinalAggregate.scala, src/main/scala/com/nec/spark/planning/plans/VeFlattenPartition.scala, src/main/scala/com/nec/spark/planning/plans/VeOneStageEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/plans/VePartialAggregate.scala, src/main/scala/com/nec/spark/planning/plans/VeProjectEvaluationPlan.scala, src/main/scala/com/nec/spark/planning/plans/VectorEngineJoinPlan.scala, src/main/scala/com/nec/spark/planning/plans/VectorEngineToSparkPlan.scala
There may be situations where the metrics are not initialized before plan execution. This forces the initialization.
=> Force initialization of Metrics before plan execution

adr/0004-Packed Transfers.md, src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone.hpp, src/main/resources/com/nec/cyclone/cpp/cyclone/cyclone_utils.hpp, src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.cc, src/main/resources/com/nec/cyclone/cpp/cyclone/packed_transfer.hpp, src/main/resources/com/nec/cyclone/cpp/tests/cyclone_utils_spec.cc, src/main/resources/com/nec/cyclone/cpp/tests/packed_transfer_spec.cc, src/main/scala/com/nec/cache/ArrowBasedCacheSerializer.scala, src/main/scala/com/nec/cache/ColumnarBatchToVeColBatch.scala, src/main/scala/com/nec/cache/CycloneCacheBase.scala, src/main/scala/com/nec/cache/InVectorEngineCacheSerializer.scala, src/main/scala/com/nec/cache/TransferDescriptor.scala, src/main/scala/com/nec/colvector/BytePointerColVector.scala, src/main/scala/com/nec/spark/planning/VERewriteStrategy.scala, src/main/scala/com/nec/spark/planning/VeColumnarRule.scala, src/main/scala/com/nec/spark/planning/plans/SparkToVectorEnginePlan.scala, src/main/scala/com/nec/ve/VeProcess.scala, src/test/scala/com/nec/ve/DualModeVESpec.scala
Transfer an entire partition in SparkToVectorEnginePlan.
See ADR 0004-Packed Transfers.md for details on that.
=> [NS-29] Partition level transfer

src/main/scala/com/nec/colvector/SparkSqlColumnVectorConversions.scala
Simple change to investigate if using the array versions of the get methods have any performance advantages.
=> Use getLongs/Doubles etc. if ColumnVector has no nulls.

src/main/scala/com/nec/cache/RowCollectingTransferDescriptor.scala
Turns out that the UTF8String you get from it will change underneath you. In particular the piece of memory it points to will change, so that when you actually need to read it, you will get some kind of Garbage.
For this reason, this bugfix directly turns the UTF8String into the UTF32-LE encoded bytes we are going to need later on.
=> Bugfix: Don't hold on to UTF8String taken from InternalRow

aveobench/src/main/scala/com/nec/cyclone/colvector/CompressedBytePointerColVector.scala, src/main/scala/com/nec/cache/BpcvTransferDescriptor.scala, src/main/scala/com/nec/cache/TransferDescriptor.scala, src/main/scala/com/nec/cache/UcvTransferDescriptor.scala, src/main/scala/com/nec/colvector/BytePointerColVector.scala, src/main/scala/com/nec/colvector/ColVectorLike.scala, src/main/scala/com/nec/colvector/UnitColVector.scala, src/main/scala/com/nec/colvector/VeColVector.scala
Summary:
- Consolidate computation of header, data, and result buffer offsets into the same set of method
=> [NS-55] Code clean ups
